### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wainyz** [NotInWine/xmind-to-md#1]
![image](https://github.com/NotInWine/xmind-to-md/assets/126802333/6aab657a-6c48-46e6-b6d7-b49f1eddc8b4)

**Comment by wainyz** [comment]
Faild to load META-INF/manifest.xml
org.xmind.core.CoreException: No such entry: META-INF/manifest.xml
	at org.xmind.core.internal.dom.WorkbookLoader.doLoadXMLFile(WorkbookLoader.java:377)
	at org.xmind.core.internal.dom.XMLLoader.loadXMLFile(XMLLoader.java:38)
	at org.xmind.core.internal.dom.WorkbookLoader.forceLoadXML(WorkbookLoader.java:314)
	at org.xmind.core.internal.dom.WorkbookLoader.loadManifest(WorkbookLoader.java:160)
	at org.xmind.core.internal.dom.WorkbookLoader.doLoad(WorkbookLoader.java:143)
	at org.xmind.core.internal.dom.WorkbookLoader.load(WorkbookLoader.java:128)
	at org.xmind.core.internal.dom.WorkbookBuilderImpl.loadFromInputSource(WorkbookBuilderImpl.java:191)
	at org.xmind.core.internal.AbstractWorkbookBuilder.doLoadFromDirectory(AbstractWorkbookBuilder.java:132)
	at org.xmind.core.internal.AbstractWorkbookBuilder.loadFromFile(AbstractWorkbookBuilder.java:111)
	at org.xmind.core.internal.AbstractWorkbookBuilder.doLoadFromPath(AbstractWorkbookBuilder.java:72)
	at org.xmind.core.internal.AbstractWorkbookBuilder.loadFromPath(AbstractWorkbookBuilder.java:66)
	at org.xmind.core.internal.AbstractWorkbookBuilder.loadFromPath(AbstractWorkbookBuilder.java:40)
	at com.yxy.util.XMindUtils.readRootTopic(XMindUtils.java:21)
	at com.yxy.to.md.XMindToMd.toMD(XMindToMd.java:39)
	at com.yxy.to.md.ToMdUtils.toMD(ToMdUtils.java:33)
	at com.yxy.demo.Main.main(Main.java:14)
Faild to load meta.xml
org.xmind.core.CoreException: No such entry: meta.xml
	at org.xmind.core.internal.dom.WorkbookLoader.doLoadXMLFile(WorkbookLoader.java:377)
	at org.xmind.core.internal.dom.XMLLoader.loadXMLFile(XMLLoader.java:38)
	at org.xmind.core.internal.dom.WorkbookLoader.forceLoadXML(WorkbookLoader.java:314)
	at org.xmind.core.internal.dom.WorkbookLoader.loadMeta(WorkbookLoader.java:181)
	at org.xmind.core.internal.dom.WorkbookLoader.doLoad(WorkbookLoader.java:149)
	at org.xmind.core.internal.dom.WorkbookLoader.load(WorkbookLoader.java:128)
	at org.xmind.core.internal.dom.WorkbookBuilderImpl.loadFromInputSource(WorkbookBuilderImpl.java:191)
	at org.xmind.core.internal.AbstractWorkbookBuilder.doLoadFromDirectory(AbstractWorkbookBuilder.java:132)
	at org.xmind.core.internal.AbstractWorkbookBuilder.loadFromFile(AbstractWorkbookBuilder.java:111)
	at org.xmind.core.internal.AbstractWorkbookBuilder.doLoadFromPath(AbstractWorkbookBuilder.java:72)
	at org.xmind.core.internal.AbstractWorkbookBuilder.loadFromPath(AbstractWorkbookBuilder.java:66)
	at org.xmind.core.internal.AbstractWorkbookBuilder.loadFromPath(AbstractWorkbookBuilder.java:40)
	at com.yxy.util.XMindUtils.readRootTopic(XMindUtils.java:21)
	at com.yxy.to.md.XMindToMd.toMD(XMindToMd.java:39)
	at com.yxy.to.md.ToMdUtils.toMD(ToMdUtils.java:33)
	at com.yxy.demo.Main.main(Main.java:14)

**Comment by wainyz** [comment]
网上找到原因了,是我使用的xmind版本对不上

**Comment by NotInWine** [comment]
ok
